//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cwmsys.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_CD5000                      104
#define IDD_AE500                       105
#define IDR_MAINFRAME                   128
#define IDD_SETUP_DIALOG                129
#define IDD_PARA_DIALOG                 136
#define IDR_MENU                        137
#define IDD_STANDARD_VAL                138
#define IDD_DIALOG1                     143
#define IDD_DATADISPLAY_DIALOG          143
#define IDC_PICTURE                     1000
#define IDC_PIC_REAL                    1000
#define IDC_BTN_SETUP                   1001
#define IDC_BTN_SAVE                    1002
#define IDC_CCD5000_BAUDRATE            1003
#define IDC_BUTTON1                     1003
#define IDC_BTN_PARA                    1003
#define IDC_BUTTONQUERY                 1003
#define IDC_CCD5000_DATABITS            1004
#define IDC_STATIC_TOP1                 1004
#define IDC_BTN_STANDARD                1004
#define IDC_BUTTONMAINQUERY             1004
#define IDC_CCD5000_STOPBITS            1005
#define IDC_STATIC_TOP2                 1005
#define IDC_CCD5000_PARITY              1006
#define IDC_STATIC_TOP3                 1006
#define IDC_CCD5000_TIMEOUT             1007
#define IDC_STATIC_TOP4                 1007
#define IDC_CCD5000_PORT                1008
#define IDC_STATIC_TOP5                 1008
#define IDC_AE500_PORT                  1009
#define IDC_STATIC_TOP6                 1009
#define IDC_AE500_BAUDRATE              1010
#define IDC_STATIC_TOP7                 1010
#define IDC_AE500_DATABITS              1011
#define IDC_STATIC_BOTTOM1              1011
#define IDC_AE500_STOPBITS              1012
#define IDC_STATIC_BOTTOM2              1012
#define IDC_AE500_PARITY                1013
#define IDC_STATIC_BOTTOM3              1013
#define IDC_AE500_TIMEOUT               1014
#define IDC_STATIC_BOTTOM4              1016
#define IDC_STATIC_BOTTOM5              1017
#define IDC_LIST_INFO                   1018
#define IDC_STATIC_BOTTOM6              1019
#define IDC_STATIC_BOTTOM7              1020
#define IDC_BTN_MANUAL                  1021
#define IDC_BTN_ANTO                    1022
#define IDC_EDIT_TONGJI                 1023
#define IDC_EDIT_UPPER                  1024
#define IDC_PIC_GRAP_LEFT               1024
#define IDC_PIC_LEFT_DOWN               1024
#define IDC_EDIT3                       1025
#define IDC_EDIT_LOWER                  1025
#define IDC_PIC_GRAP_RIGHT              1025
#define IDC_PIC_RIGHT_DOWN              1025
#define IDC_EDIT_MES_EQ                 1025
#define IDC_EDIT_WARNER                 1025
#define IDC_EDIT_ALARM                  1025
#define IDC_EDIT_NUM                    1026
#define IDC_EDIT_ROOL_NUM               1026
#define IDC_EDIT_MATERIAL_WIDTH         1026
#define IDC_PIC_LEFT_UP                 1026
#define IDC_EDIT_UPEAR_WIDTH            1026
#define IDC_EDIT2                       1027
#define IDC_EDIT_EAR_WIDTH              1027
#define IDC_EDIT_MES_PC                 1027
#define IDC_EDIT_UPEAR_WIDTH3           1027
#define IDC_EDIT_UPEAR_WIDTH2           1028
#define IDC_PIC_RIGHT_DOWN2             1029
#define IDC_PIC_RIGHT_UP                1029
#define IDC_EDIT_UPEAR_WIDTH4           1029
#define IDC_COMBO_SHOW                  1030
#define IDC_RADIO1                      1031
#define IDC_RADIO_SET                   1031
#define IDC_EDIT_UPMATERIAL_WIDTH       1031
#define IDC_RADIO_AUTO                  1032
#define IDC_EDIT_UPMATERIAL_WIDTH3      1032
#define IDC_EDIT_UPMATERIAL_WIDTH2      1033
#define IDC_BUTTON2                     1035
#define IDC_BUTTONSQL                   1035
#define IDC_BUTTONEXPORTDATA            1035
#define IDC_IP_MES                      1036
#define IDC_EDIT_PORT_MES               1037
#define IDC_COMBO1                      1038
#define IDC_COMBO_STUTES                1038
#define IDC_EDIT_DOWNEAR_WIDTH          1038
#define IDC_COMBO_POSITIVE              1038
#define IDC_EDIT_EARLYWARMING           1039
#define IDC_LIST1                       1040
#define IDC_EDIT_DOWNEAR_WIDTH3         1040
#define IDC_BUTTONONOK                  1041
#define IDC_EDIT_DOWNEAR_WIDTH2         1041
#define IDC_BUTTONADD                   1042
#define IDC_EDIT_DOWNEAR_WIDTH4         1042
#define IDC_DEL                         1043
#define IDC_EDITDATETIME                1044
#define IDC_EDIT_ORDERNUMBER            1044
#define IDC_EDITBREED                   1045
#define IDC_EDIT_ROOLNAME               1045
#define IDC_EDITDATA1                   1046
#define IDC_EDIT_DOWNMATERIAL_WIDTH     1046
#define IDC_EDITDATA3                   1047
#define IDC_EDIT_DOWNMATERIAL_WIDTH3    1047
#define IDC_EDITORDERNUMBER             1048
#define IDC_EDIT_DOWNMATERIAL_WIDTH2    1048
#define IDC_LIST3                       1048
#define IDC_EDITOPERATIONALSOURCE       1049
#define IDC_EDITEAR_WIDTH5              1049
#define IDC_EDITEAR_WIDTH               1049
#define IDC_EDIT                        1049
#define IDC_EDITDATA2                   1050
#define IDC_EDITMATERIAL_WIDTH          1050
#define IDC_BUTTON3                     1050
#define IDC_BUTTONDATADEL               1050
#define IDC_EDITDATA4                   1051
#define IDC_COMBO_AT9                   1051
#define IDC_IMG_WIDTH_TOP               1052
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_DISPLAY_SET                  32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
